// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/auth/auth_service.proto

package auth

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPasswd    string                 `protobuf:"bytes,2,opt,name=user_passwd,json=userPasswd,proto3" json:"user_passwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestType) Reset() {
	*x = RequestType{}
	mi := &file_proto_auth_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestType) ProtoMessage() {}

func (x *RequestType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestType.ProtoReflect.Descriptor instead.
func (*RequestType) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RequestType) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RequestType) GetUserPasswd() string {
	if x != nil {
		return x.UserPasswd
	}
	return ""
}

type ResponseType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseType) Reset() {
	*x = ResponseType{}
	mi := &file_proto_auth_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseType) ProtoMessage() {}

func (x *ResponseType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseType.ProtoReflect.Descriptor instead.
func (*ResponseType) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseType) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

var File_proto_auth_auth_service_proto protoreflect.FileDescriptor

const file_proto_auth_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/auth/auth_service.proto\x12\x04auth\"K\n" +
	"\vRequestType\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_passwd\x18\x02 \x01(\tR\n" +
	"userPasswd\"*\n" +
	"\fResponseType\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse2H\n" +
	"\vAuthService\x129\n" +
	"\x10AuthenticateUser\x12\x11.auth.RequestType\x1a\x12.auth.ResponseTypeB\n" +
	"Z\bpkg/authb\x06proto3"

var (
	file_proto_auth_auth_service_proto_rawDescOnce sync.Once
	file_proto_auth_auth_service_proto_rawDescData []byte
)

func file_proto_auth_auth_service_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_service_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_service_proto_rawDesc), len(file_proto_auth_auth_service_proto_rawDesc)))
	})
	return file_proto_auth_auth_service_proto_rawDescData
}

var file_proto_auth_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_auth_auth_service_proto_goTypes = []any{
	(*RequestType)(nil),  // 0: auth.RequestType
	(*ResponseType)(nil), // 1: auth.ResponseType
}
var file_proto_auth_auth_service_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.AuthenticateUser:input_type -> auth.RequestType
	1, // 1: auth.AuthService.AuthenticateUser:output_type -> auth.ResponseType
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_service_proto_init() }
func file_proto_auth_auth_service_proto_init() {
	if File_proto_auth_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_service_proto_rawDesc), len(file_proto_auth_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_service_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_service_proto_depIdxs,
		MessageInfos:      file_proto_auth_auth_service_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_service_proto = out.File
	file_proto_auth_auth_service_proto_goTypes = nil
	file_proto_auth_auth_service_proto_depIdxs = nil
}
